dataset_params:
  im_path: '/dir/DiffuseSeg/data/celebahq64_sample/train/'

diffusion_params:
  num_timesteps : 1000
  beta_start : 0.0001
  beta_end : 0.02

model_params:
  im_channels: 3
  im_size: 64
  down_channels: [64, 128, 256, 512]  
  mid_channels: [512, 512, 256]       
  down_sample: [True, True, True]
  time_emb_dim: 256
  num_down_layers: 2
  num_mid_layers: 2
  num_up_layers: 2
  num_heads: 4

train_params:
  type : 'resume'
  model_path : '/dir/DiffuseSeg/weights/DDPM_Celeb_wts_10k_2/DDPM_Celeb_11.pth'
  batch_size: 16
  num_epochs: 200
  num_samples : 25
  lr: 0.0001
  ckpt_path: '/dir/DiffuseSeg/weights/DDPM_Celeb_wts_10k_2/'

infer_params:
  model_path : "/dir/DiffuseSeg/weights/DDPM_Celeb_wts_2/DDPM_Celeb_151.pth"
  save_dir : "/dir/DiffuseSeg/weights/DDPM_Celeb_wts_2/samples_ep150/"
  num_samples : 10